spring:
  application:
    name: gateway-server
  profiles:
    active: default
  cloud:
    config:
      url: http://localhost:8071
      enabled: true

    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

  config:
    import: "configserver:"

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, mappings
    enabled-by-default: true