spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://config-server:8071
      enabled: true
    loadbalancer:
      ribbon:
       enabled: false
  config:
    import: "configserver:"